/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.odm.multit;

import java.util.LinkedList;
import java.util.List;
import java.util.OptionalDouble;
import java.util.stream.LongStream;

import org.apache.commons.lang3.time.StopWatch;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        StopWatch watch = new StopWatch();
        watch.start();
        WordCountService.GenerateWordCount();
        watch.stop();

        System.out.println("Done, elapsed time: " + watch.getTime());

        Integer n = 10;
        List<Long> elapsedTimesSingle = new LinkedList<Long>();
        List<Long> elapsedTimesMulti = new LinkedList<Long>();

        for (Integer i = 0; i < n; i++ ) {
            watch.reset();
            watch.start();
            WordCountService.GenerateWordCount();
            watch.stop();
            elapsedTimesSingle.add(watch.getTime());    
        }

        for (Integer i = 0; i < n; i++ ) {
            watch.reset();
            watch.start();
            WordCountServiceMultiT.GenerateWordCount();
            watch.stop();
            elapsedTimesMulti.add(watch.getTime());
        }


        OptionalDouble lss = elapsedTimesSingle.stream().mapToLong(l -> l).average();
        OptionalDouble lsm = elapsedTimesMulti.stream().mapToLong(l -> l).average();
        System.out.println("Elapsed time single: " + (long)lss.getAsDouble());
        System.out.println("Elapsed time multi:  " + (long)lsm.getAsDouble());

    }
}
